# Generated by Django 6.0.7 on 2026-07-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionWebpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=50, verbose_name='Orden de Compra')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID de Sesión')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token WS')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(max_length=50, verbose_name='Estado TBK')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='orders.orden')),
            ],
        ),
        migrations.CreateModel(
            name='LogPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(verbose_name='Respuesta Raw Transbank')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.transaccionwebpay')),
            ],
        ),
    ]
