# Generated by Django 6.0.7 on 2026-07-21 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_carrito_options_alter_historialestado_options_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logpago',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Log de pago', 'verbose_name_plural': 'Logs de pago'},
        ),
        migrations.AlterModelOptions(
            name='transaccionwebpay',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Transacción Webpay', 'verbose_name_plural': 'Transacciones Webpay'},
        ),
        migrations.AddField(
            model_name='logpago',
            name='evento',
            field=models.CharField(choices=[('CREATE', 'Creación de transacción'), ('COMMIT', 'Confirmación de pago'), ('ERROR', 'Error'), ('RETURN', 'Retorno Webpay')], default='RETURN', max_length=20, verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de autorización'),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='installments_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de cuota'),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='installments_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de cuotas'),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='payment_type_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='transaccionwebpay',
            name='response_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código de respuesta'),
        ),
        migrations.AlterField(
            model_name='logpago',
            name='raw_response',
            field=models.JSONField(verbose_name='Respuesta raw de Transbank'),
        ),
        migrations.AlterField(
            model_name='transaccionwebpay',
            name='buy_order',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Orden de compra'),
        ),
        migrations.AlterField(
            model_name='transaccionwebpay',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='orders.orden'),
        ),
        migrations.AlterField(
            model_name='transaccionwebpay',
            name='session_id',
            field=models.CharField(max_length=128, verbose_name='ID de sesión'),
        ),
        migrations.AlterField(
            model_name='transaccionwebpay',
            name='status',
            field=models.CharField(choices=[('INICIADA', 'Iniciada'), ('AUTHORIZED', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('FALLIDA', 'Fallida'), ('ERROR', 'Error'), ('EXPIRADA', 'Expirada'), ('ANULADA', 'Anulada')], default='INICIADA', max_length=20, verbose_name='Estado Transbank'),
        ),
        migrations.AddConstraint(
            model_name='transaccionwebpay',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'AUTHORIZED')), fields=('orden',), name='unique_transaccion_autorizada_por_orden'),
        ),
    ]
