# Generated by Django 6.0.7 on 2026-07-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_perfilvendedor_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaOptica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfera_od', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera Ojo Derecho')),
                ('esfera_oi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera Ojo Izquierdo')),
                ('cilindro_od', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro Ojo Derecho')),
                ('cilindro_oi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro Ojo Izquierdo')),
                ('eje_od', models.IntegerField(blank=True, null=True, verbose_name='Eje Ojo Derecho')),
                ('eje_oi', models.IntegerField(blank=True, null=True, verbose_name='Eje Ojo Izquierdo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='accounts.perfilcliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Público')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='store.categoria')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_no_negativo')],
            },
        ),
    ]
