# Generated by Django 6.0.7 on 2026-07-21 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='recetaoptica',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Receta óptica', 'verbose_name_plural': 'Recetas ópticas'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de aparición'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Si se desmarca, el producto no aparece en la tienda pública.', verbose_name='Visible en catálogo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destacado en home'),
        ),
        migrations.AddField(
            model_name='recetaoptica',
            name='add_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Adición OD'),
        ),
        migrations.AddField(
            model_name='recetaoptica',
            name='add_oi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Adición OI'),
        ),
        migrations.AddField(
            model_name='recetaoptica',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetaoptica',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de categoría'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio público'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='cilindro_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro OD'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='cilindro_oi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cilindro OI'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='eje_od',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eje OD (0-180)'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='eje_oi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eje OI (0-180)'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='esfera_od',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera ojo derecho (OD)'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='esfera_oi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera ojo izquierdo (OI)'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_no_negativo'),
        ),
    ]
