# Generated by Django 6.0.7 on 2026-07-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='recetaoptica',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Receta optica', 'verbose_name_plural': 'Recetas opticas'},
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Codigo unico de catalogo. Se autogenera si se deja vacio.', max_length=40, null=True, unique=True, verbose_name='SKU / Codigo unico'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de aparicion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Visible en catalogo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio publico'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='add_od',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Adicion OD'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='add_oi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Adicion OI'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='esfera_od',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera OD'),
        ),
        migrations.AlterField(
            model_name='recetaoptica',
            name='esfera_oi',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Esfera OI'),
        ),
    ]
