# Generated by Django 6.0.7 on 2026-07-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_categoria_options_alter_recetaoptica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Cuando el stock cae a este valor o menos, se dispara una alerta.', verbose_name='Stock minimo (alerta)'),
        ),
    ]
