# Generated by Django 6.0.7 on 2026-08-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Color (etiqueta)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='grupo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Productos con el mismo grupo se muestran como una sola tarjeta con selector de color.', max_length=60, verbose_name='Grupo/Familia (colores)'),
        ),
    ]
