# Generated by Django 6.0.7 on 2026-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_producto_color_producto_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='configurable_lente',
            field=models.BooleanField(default=False, help_text='Si se activa, el catalogo ofrece elegir diseno focal y distancia de uso.', verbose_name='Configurable como lente (tipo y distancia)'),
        ),
    ]
