# Generated by Django 6.0.7 on 2026-09-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_producto_configurable_lente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_tryon',
            field=models.ImageField(blank=True, help_text='PNG frontal con fondo transparente para superponer en el rostro en el probador virtual.', null=True, upload_to='productos/tryon/', verbose_name='Imagen PNG frontal transparente (Probador virtual)'),
        ),
    ]
