# Generated by Django 6.0.7 on 2026-07-21 19:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilvendedor_sucursal'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'verbose_name': 'Perfil cliente', 'verbose_name_plural': 'Perfiles cliente'},
        ),
        migrations.AlterModelOptions(
            name='perfilvendedor',
            options={'verbose_name': 'Perfil vendedor', 'verbose_name_plural': 'Perfiles vendedor'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('ADMIN', 'Administrador')], db_index=True, default='CLIENTE', max_length=10, verbose_name='Rol de usuario'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de despacho'),
        ),
        migrations.AlterField(
            model_name='perfilvendedor',
            name='codigo_vendedor',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código vendedor'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['CLIENTE', 'VENDEDOR', 'ADMIN'])), name='accounts_user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='perfilcliente',
            constraint=models.CheckConstraint(condition=models.Q(('rut', ''), _negated=True), name='perfil_cliente_rut_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='perfilvendedor',
            constraint=models.CheckConstraint(condition=models.Q(('codigo_vendedor', ''), _negated=True), name='perfil_vend_codigo_not_empty'),
        ),
    ]
