# Generated by Django 6.0.7 on 2026-07-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_perfilcliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False, help_text='True para compradores invitados creados sin contraseña.', verbose_name='Cuenta invitada (sin contraseña)'),
        ),
    ]
