# Generated by Django 6.0.7 on 2026-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='region',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Región'),
        ),
    ]
