# Generated by Django 6.0.7 on 2026-08-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_perfilcliente_comuna_perfilcliente_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono de contacto'),
        ),
    ]
