# Generated by Django 6.0.7 on 2026-09-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_comuna_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acepta_terminos',
            field=models.BooleanField(default=False, verbose_name='Acepta terminos y privacidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='acepta_terminos_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha aceptacion terminos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='acepta_terminos_version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Version terminos aceptada'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consiente_marketing',
            field=models.BooleanField(default=False, verbose_name='Consiente ofertas y promociones'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consiente_salud',
            field=models.BooleanField(default=False, verbose_name='Consiente tratamiento de datos de salud'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consiente_salud_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha consentimiento salud'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consiente_salud_version',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Version consentimiento salud'),
        ),
    ]
