# Generated by Django 6.0.7 on 2026-09-25 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email registrado al momento')),
                ('tipo', models.CharField(choices=[('TERMINOS', 'Términos y Privacidad'), ('SALUD', 'Tratamiento de Datos de Salud'), ('MARKETING', 'Comunicaciones y Marketing')], max_length=20, verbose_name='Tipo de consentimiento')),
                ('accion', models.CharField(choices=[('OTORGADO', 'Consentimiento Otorgado'), ('REVOCADO', 'Consentimiento Revocado')], max_length=15, verbose_name='Acción realizada')),
                ('version', models.CharField(blank=True, default='', max_length=20, verbose_name='Versión de política')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='Navegador / User-Agent')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_consentimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de consentimiento',
                'verbose_name_plural': 'Logs de consentimiento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSupresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_original', models.EmailField(max_length=254, verbose_name='Email original del titular')),
                ('rut_asociado', models.CharField(blank=True, default='', max_length=12, verbose_name='RUT asociado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo declarado por el usuario')),
                ('detalle_resguardo', models.TextField(default='Cuenta desactivada y datos de contacto/marketing anonimizados. Prescripciones ópticas retenidas por 15 años (Ley 20.584 / D.S. 41 MINSAL) y registros tributarios retenidos por 6 años (SII) en archivo pasivo legal.', verbose_name='Detalle de resguardo legal aplicado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_supresion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de supresión de datos',
                'verbose_name_plural': 'Solicitudes de supresión de datos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
