# Generated by Django 6.0.7 on 2026-09-25 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OPTICA', 'Receta de lentes (optica)'), ('CONTACTOLOGIA', 'Receta de lentes de contacto'), ('OTRO', 'Otro documento visual')], default='OPTICA', max_length=20)),
                ('archivo', models.FileField(upload_to='recetas/%Y/%m/')),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('detalle', models.TextField(blank=True, default='')),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
