# Generated by Django 6.0.7 on 2026-09-25 20:10

import recetas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='archivo',
            field=models.FileField(upload_to=recetas.models.receta_upload_path),
        ),
    ]
