# Generated by Django 6.0.7 on 2026-07-21 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologos', to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('tecnologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='appointments.tecnologo')),
            ],
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='AGENDADA', max_length=20, verbose_name='Estado')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('bloque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cita', to='appointments.bloquehorario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bloque',), name='cita_unica_por_bloque')],
            },
        ),
    ]
