# Generated by Django 6.0.7 on 2026-07-21 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloquehorario',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Bloque horario', 'verbose_name_plural': 'Bloques horarios'},
        ),
        migrations.AlterModelOptions(
            name='citamedica',
            options={'ordering': ['-fecha_reserva'], 'verbose_name': 'Cita médica', 'verbose_name_plural': 'Citas médicas'},
        ),
        migrations.AlterModelOptions(
            name='tecnologo',
            options={'ordering': ['nombre'], 'verbose_name': 'Tecnólogo', 'verbose_name_plural': 'Tecnólogos'},
        ),
        migrations.RemoveConstraint(
            model_name='citamedica',
            name='cita_unica_por_bloque',
        ),
        migrations.AddField(
            model_name='tecnologo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='disponible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='fecha',
            field=models.DateField(db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='bloquehorario',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='estado',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], db_index=True, default='AGENDADA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='citamedica',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva'),
        ),
        migrations.AlterField(
            model_name='tecnologo',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AddConstraint(
            model_name='bloquehorario',
            constraint=models.UniqueConstraint(fields=('tecnologo', 'fecha', 'hora_inicio'), name='bloque_unico_tecnologo_fecha_inicio'),
        ),
        migrations.AddConstraint(
            model_name='citamedica',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['AGENDADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA', 'NO_ASISTIO'])), name='cita_estado_valido'),
        ),
    ]
