# Generated by Django 6.0.7 on 2026-07-21 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-cambiado_en'], 'verbose_name': 'Historial de estado', 'verbose_name_plural': 'Historiales de estado'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item de carrito', 'verbose_name_plural': 'Items de carrito'},
        ),
        migrations.AlterModelOptions(
            name='itemorden',
            options={'verbose_name': 'Item de orden', 'verbose_name_plural': 'Items de orden'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AddField(
            model_name='historialestado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_estado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparación'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparación'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='item_carrito_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemorden',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='item_orden_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itemorden',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='item_orden_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'PAGADA', 'EN_PREPARACION', 'ENVIADA', 'ENTREGADA', 'CANCELADA', 'FALLIDA'])), name='orden_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='orden_total_no_negativo'),
        ),
    ]
