# Generated by Django 6.0.7 on 2026-07-23 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_carrito_options_alter_historialestado_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.RemoveConstraint(
            model_name='orden',
            name='orden_estado_valido',
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo',
            field=models.CharField(blank=True, help_text='Codigo legible y no secuencial (ej. MV-2026-48271). Se autogenera.', max_length=20, null=True, unique=True, verbose_name='Codigo de pedido'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparacion'), ('LISTO_PARA_RETIRO', 'Listo para retiro'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparacion'), ('LISTO_PARA_RETIRO', 'Listo para retiro'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'PAGADA', 'EN_PREPARACION', 'LISTO_PARA_RETIRO', 'ENVIADA', 'ENTREGADA', 'CANCELADA', 'FALLIDA'])), name='orden_estado_valido'),
        ),
    ]
