# Generated by Django 6.0.7 on 2026-07-24 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orden_options_remove_orden_orden_estado_valido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo del cliente')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=12, verbose_name='Estado')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo (vendedor)')),
                ('reembolso_procesado', models.BooleanField(default=False, verbose_name='Reembolso procesado (manual)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de devolucion',
                'verbose_name_plural': 'Solicitudes de devolucion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='orden',
            name='orden_estado_valido',
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparacion'), ('LISTO_PARA_RETIRO', 'Listo para retiro'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida'), ('DEVUELTA', 'Devuelta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('EN_PREPARACION', 'En preparacion'), ('LISTO_PARA_RETIRO', 'Listo para retiro'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada'), ('FALLIDA', 'Fallida'), ('DEVUELTA', 'Devuelta')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'PAGADA', 'EN_PREPARACION', 'LISTO_PARA_RETIRO', 'ENVIADA', 'ENTREGADA', 'CANCELADA', 'FALLIDA', 'DEVUELTA'])), name='orden_estado_valido'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_devolucion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='orders.orden'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_resueltas', to=settings.AUTH_USER_MODEL),
        ),
    ]
