# Generated by Django 6.0.7 on 2026-08-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_solicituddevolucion_remove_orden_orden_estado_valido_and_more'),
        ('store', '0004_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Se sella automaticamente al pasar a ENTREGADA. Ancla el reloj de garantias.', null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.CreateModel(
            name='PoliticaGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Slug estable p/ el seed (ej. legal, tecnica_armazon).', max_length=40, unique=True, verbose_name='Código interno')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('base', models.CharField(choices=[('LEGAL', 'Garantía legal'), ('FABRICANTE', 'Técnica / fabricante'), ('CONFORT', 'Adaptación / confort')], db_index=True, max_length=20, verbose_name='Base')),
                ('descripcion', models.TextField(verbose_name='Cobertura')),
                ('exclusiones', models.TextField(blank=True, verbose_name='Exclusiones')),
                ('plazo_label', models.CharField(help_text='Etiqueta humana: "6 meses", "30 a 60 días".', max_length=40, verbose_name='Plazo (texto)')),
                ('plazo_dias_min', models.PositiveIntegerField(verbose_name='Plazo mínimo (días)')),
                ('plazo_dias_max', models.PositiveIntegerField(help_text='Hasta aquí corre el reloj de vigencia.', verbose_name='Plazo máximo (días)')),
                ('activa', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('orden_prioridad', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('permite_devolucion', models.BooleanField(default=False, verbose_name='Permite devolución')),
                ('permite_cambio', models.BooleanField(default=False, verbose_name='Permite cambio')),
                ('permite_reparacion', models.BooleanField(default=False, verbose_name='Permite reparación')),
                ('permite_rehacer', models.BooleanField(default=False, verbose_name='Permite re-hacer (multifocal)')),
                ('solo_con_receta', models.BooleanField(default=False, verbose_name='Solo con receta óptica')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Vacío = aplica a toda compra (refinado en nivel Completo).', related_name='politicas_garantia', to='store.categoria')),
            ],
            options={
                'verbose_name': 'Política de garantía',
                'verbose_name_plural': 'Políticas de garantía',
                'ordering': ['orden_prioridad', 'nombre'],
            },
        ),
    ]
