# Generated by Django 6.0.7 on 2026-08-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orden_fecha_entrega_politicagarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddevolucion',
            name='garantia_aplicada',
            field=models.CharField(blank=True, help_text='Codigo de la PoliticaGarantia bajo la que se resolvio el caso.', max_length=40, null=True, verbose_name='Garantia aplicada (codigo de politica)'),
        ),
        migrations.AddField(
            model_name='solicituddevolucion',
            name='resolucion',
            field=models.CharField(blank=True, choices=[('devolucion', 'Devolucion del dinero'), ('cambio', 'Cambio directo'), ('reparacion', 'Reparacion gratuita'), ('rehacer', 'Re-hacer (multifocal)')], help_text='Solo "devolucion" mueve el estado de la orden a DEVUELTA y repone stock.', max_length=16, null=True, verbose_name='Resolucion aplicada'),
        ),
    ]
