# Generated by Django 6.0.7 on 2026-08-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_solicituddevolucion_garantia_aplicada_and_more'),
        ('store', '0004_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddevolucion',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Lineas de la orden que se devuelven. Vacio en solicitudes legacy.', related_name='devoluciones', to='orders.itemorden'),
        ),
        migrations.AlterField(
            model_name='politicagarantia',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='politicas_garantia', to='store.categoria'),
        ),
        migrations.AlterField(
            model_name='politicagarantia',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='politicagarantia',
            name='plazo_dias_max',
            field=models.PositiveIntegerField(verbose_name='Plazo máximo (días)'),
        ),
        migrations.AlterField(
            model_name='politicagarantia',
            name='plazo_label',
            field=models.CharField(max_length=40, verbose_name='Plazo (texto)'),
        ),
        migrations.AlterField(
            model_name='solicituddevolucion',
            name='garantia_aplicada',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Garantia aplicada (codigo de politica)'),
        ),
        migrations.AlterField(
            model_name='solicituddevolucion',
            name='resolucion',
            field=models.CharField(blank=True, choices=[('devolucion', 'Devolucion del dinero'), ('cambio', 'Cambio directo'), ('reparacion', 'Reparacion gratuita'), ('rehacer', 'Re-hacer (multifocal)')], help_text='Solo "devolucion" repone stock; la orden pasa a DEVUELTA solo si se devuelven todas sus lineas.', max_length=16, null=True, verbose_name='Resolucion aplicada'),
        ),
    ]
