# Generated by Django 6.0.7 on 2026-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_solicituddevolucion_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='modo_pago',
            field=models.CharField(choices=[('COMPLETO', 'Pago completo'), ('ABONO', 'Abono 50% + saldo en tienda')], default='COMPLETO', max_length=10, verbose_name='Modalidad de pago'),
        ),
        migrations.AddField(
            model_name='orden',
            name='monto_abonado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto abonado online'),
        ),
        migrations.AddField(
            model_name='orden',
            name='saldo_cancelado',
            field=models.BooleanField(default=False, verbose_name='Saldo cancelado en tienda'),
        ),
        migrations.AddField(
            model_name='orden',
            name='saldo_cancelado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelacion del saldo'),
        ),
    ]
