# Generated by Django 6.0.7 on 2026-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orden_modo_pago_orden_monto_abonado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='tipo_lente',
            field=models.CharField(blank=True, choices=[('MONOFOCAL', 'Monofocal (foco unico)'), ('BIFOCAL', 'Bifocal (doble foco)'), ('PROGRESIVO', 'Progresivo / multifocal'), ('OCUPACIONAL', 'Ocupacional / degresivo')], default='', max_length=16, verbose_name='Tipo de lente'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='uso_lente',
            field=models.CharField(blank=True, choices=[('LEJOS', 'Vision lejos'), ('CERCA', 'Vision cerca (lectura)'), ('LEJOS_CERCA', 'Lejos y cerca'), ('INTERMEDIA', 'Intermedia (pantallas 40 cm - 2 m)')], default='', max_length=16, verbose_name='Uso / distancia'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='tipo_lente',
            field=models.CharField(blank=True, choices=[('MONOFOCAL', 'Monofocal (foco unico)'), ('BIFOCAL', 'Bifocal (doble foco)'), ('PROGRESIVO', 'Progresivo / multifocal'), ('OCUPACIONAL', 'Ocupacional / degresivo')], default='', max_length=16, verbose_name='Tipo de lente'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='uso_lente',
            field=models.CharField(blank=True, choices=[('LEJOS', 'Vision lejos'), ('CERCA', 'Vision cerca (lectura)'), ('LEJOS_CERCA', 'Lejos y cerca'), ('INTERMEDIA', 'Intermedia (pantallas 40 cm - 2 m)')], default='', max_length=16, verbose_name='Uso / distancia'),
        ),
    ]
