# Generated by Django 6.0.7 on 2026-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_itemcarrito_tipo_lente_itemcarrito_uso_lente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddevolucion',
            name='cantidades',
            field=models.JSONField(blank=True, default=dict, help_text='Vacio = devolucion de la linea completa (legado).', verbose_name='Cantidades devueltas por linea (item_id -> cantidad)'),
        ),
    ]
