# Generated by Django 6.0.7 on 2026-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_solicituddevolucion_cantidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de cancelacion'),
        ),
    ]
